### ISSUE TITLE
QA Review by Product

### ISSUE THREAD

**Issue by aassoiants** [bitcoinsearch/bitcoinsearch-app#111] opened 2024-04-19 00:06 UTC
First off - great work so far. We've very close!

# Overall
- [x] A Can someone please show me the link preview image and copy?
- [ ] B Let's name our buttons to boost accessibility
	- ![Pasted image 20240418173416](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/126297088/890b62d8-ea63-483a-bd59-abc92360f93c)
- [x] C In terms of metadata, let's make sure we tackle all the usual OpenGraph/OG stuff. We did this well in bitcoindevs.xyz
	- Let's change preview link to "Search the depths of bitcoin's technical ecosystem"
- [x] D When returning back to the website - let's say i'm coming off the Search Page like [this one](https://bitcoinsearch-ljzj8mab0-btc-knowledge-base.vercel.app/?search=a&sort_sort_by=created_at%3Adesc)... it flashes the homepage for a few seconds and then goes to the appropriate link. 
- [x] E Remove Bitcoin Search from Secondary Product Menu
	- ![Pasted image 20240418172700](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/126297088/4e2c6080-d6a4-4320-ac56-1d93c77c4f89)

# Homepage
- [x] A Make the search input box font even brighter
	- ![Pasted image 20240418173134](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/126297088/159825f5-82ab-4d6a-b09b-e441e571bd70)
- [x] B Bottom of page CTA should be at least 2x smaller
	- ![image](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/126297088/2ebe9dcd-5f51-4b64-9fc4-4199611bff7f)
- [x] C Remove icons in the 3 value props and pull up the text, for example
	- ![image](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/126297088/e852bc27-ecb0-4d84-bcd8-fa6be4ec7256)
	- ![image](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/126297088/012aae6d-e6e0-4f0f-9ba5-d108697a9478)
- [x] D The "search" button in the searchbox shouldn't be clickable if the input field is empty

# Search Page
- [x] A Same as landing page - make the search bar much brighter
	- ![image](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/126297088/30297c2e-71eb-4374-820b-c14c9358b54b)
- [x] Let's keep the "showing x" results section 
- [x] B Let's increase the font of the holocat section, it's smaller than any other font we're using
	- ![image](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/126297088/526d082d-7688-4fec-9add-8ddb9e564ff0)
- [x] C Let's make sure that clicking a search result opens a new tab
- [x] D Source formatting should follow Title Case
	- "Bitcoin dev mailing list" -> "Bitcoin Dev Mailing List"
	- "BTC transcripts" -> "BTC Transcripts"
	- "LN dev mailing list" -> "LN Dev Mailing List", and the like
	- If in doubt, let's use something like this, with APA https://capitalizemytitle.com/
- [x] E When searching for something in the authors/ sources section, it doesn't remove non-relevant options. For example - as i search for "githu", i should only see sources with "githu" in the title string
	- ![Pasted image 20240418174740](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/126297088/c619a933-7cf9-4b3a-9347-ebe1e0a17105)
- [x] F For some reason i'm seeing duplicates when searching for a query in the Source list
	- ![Pasted image 20240418174804](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/126297088/1218d534-7f1e-46a1-8aab-f6c1cecb531e)

# Footer
- [x] Add a Discord logo beside the Github logo in the footer
	- [https://discord.gg/EAy9XMufbY](https://discord.gg/EAy9XMufbY "https://discord.gg/EAy9XMufbY")
	- Should be easy to find both dark and light logo version
- [x] Give Feedback in footer should link here
	- https://cryptpad.fr/form/#/2/form/view/3P2CsohsHOkcH7C+WdtX0-tvqjBHqXnAmz5D9yx0e04/

# Feedback for Designer
- [ ] A Some of our logos look pretty invisible in dark mode - we have to design a light mode version for them. For example, Delvingbitcoin & GitHub
	- ![image](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/126297088/d4cbf204-3454-4199-9fda-d068778ebcf0)
- [ ] B We need a different favicon for the product
	- ![Pasted image 20240418172744](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/126297088/6b549126-b7c7-4ee7-ab82-f0db380c2080)
- [ ] C The second image on the Landing Page should still be an image of the search page with "lightning" being the query
	- It doesn't need to be perfect or the final version of the screen - we can change it after. Just **needs** to be about lightning
	- ![Pasted image 20240418171644](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/126297088/9245339e-b256-4c30-9a9f-48293fe466fb)
- [ ] D This image looks unintentionally blurry. It doesn't look like you're trying to make the "newest sort" and "sources list" pop, which is the intention. Maybe darkening out or making even more fuzzy will help? Not a blocker for launch. 
	- ![image](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/126297088/a25e239e-d7d0-4393-876b-6271e03c2efb)
	- ![image](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/126297088/c7802193-d8bd-44e0-8da9-e1e911a0c1bc)

So close lads!

**Comment by Emmanuel-Develops** [comment] 2024-04-25 02:09
`F For some reason i'm seeing duplicates when searching for a query in the Source list`
I can't reproduce this. I think it was handled earlier as we had some duplicate domain labels. Can you check again

**Comment by Emmanuel-Develops** [comment] 2024-04-25 02:15
For A
<img width="375" alt="Screenshot 2024-04-25 at 3 13 30 AM" src="https://github.com/bitcoinsearch/bitcoinsearch-app/assets/62019510/81d49f0d-fd6b-46e9-bf87-285fe6d13c8c">

sidenote: The checklists is quite nice for structuring feedbacks

**Comment by aassoiants** [comment] 2024-04-25 02:16
@Emmanuel-Develops for Search Page F, doesn't seem like i can replicate

However, found another typo to quickly fix
- [ ] ![image](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/126297088/b7e8b28e-ff9c-46aa-8bd8-56b6ba5e5a8f)

**Comment by aassoiants** [comment] 2024-04-25 02:31
Small new nit on Homepage

- [ ] would like to make the font brighter in the secondary menu, something similar to search bar or even subheader 
![image](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/126297088/614e657a-1d14-479f-8fb6-960301570058)

**Comment by Extheoisah** [comment] 2024-05-06 09:33
closing this as completed since the issues has been addressed and the focus is now on the new staging feedback review by @adamjonas

**Closed by Extheoisah** 2024-05-06 09:33 UTC
